"""Phase 10: regenerate test_e2e_video.py from verified production API."""

import pathlib, subprocess, sys

BASE = pathlib.Path(__file__).resolve().parent
SRC = BASE / "src"
OUT = BASE / "tests" / "test_e2e_video.py"

LINES = [
    '"""E2E tests for RedactionPipeline -- verified against production exports."""',
    '',
    'from __future__ import annotations',
    '',
    'import numpy as np',
    'import pytest',
    '',
    'from PIL import Image',
    'from io import BytesIO',
    '',
    '# Production imports (verified)',
    'from consented_face_redactor.pipeline import (',
    '    RedactionPipeline,',
    '    DetectionResult,',
    '    EmbeddingResult,',
    '    MatchDecision,',
    '    ProcessResult,',
    '    TrackState,',
    ')',
    'from consented_face_redactor.gallery_matcher import GalleryMatcher',
    'from consented_face_redactor.config import Config',
    'from consented_face_redactor.effects.sticker import StickerEffect',
    'from consented_face_redactor.domain.types import FaceBox',
    '',
    '# ======= Test 1: Config default effect_mode (string) ======= #',
    'class TestConfigAndEffectMode:',
    '    def test_effect_mosaic(self) -> None:',
    '        """Config.effect_mode accepts plain string "mosaic". """',
    '        cfg = Config(effect_mode="mosaic", t_confirm=0.5)',
    '        assert cfg.effect_mode == "mosaic"',
    '',
    '# ======= Test 2: Pipeline construction via __init__ (no default()) ======= #',
    'class TestPipelineConstruction:',
    '    def test_pipeline_via_init(self) -> None:',
    '        """RedactionPipeline requires a Config; no .default() classmethod."""',
    '        cfg = Config(effect_mode="mosaic")',
    '        pipeline = RedactionPipeline(cfg, detector=None)',
    '        assert isinstance(pipeline, RedactionPipeline)',
    '        # Initial state is UNSEEN via __init__ line 181',
    '        assert pipeline.current_track_state == TrackState.UNSEEN',
    '',
    "# ======= Test 3: Confidence alone NEVER authorizes CONFIRMED ======= #",
    'class TestDetectionConfidenceGate:',
    '    def test_high_confidence_stays_candidate(self) -> None:',
    '        """Even with confidence > t_confirm, transition is CANDIDATE only."""',
    '        cfg = Config(effect_mode="mosaic")',
    '        pipeline = RedactionPipeline(cfg, detector=None)',
    '',
    '        # DetectionResult bboxes/landmarks/confidences (NO "boxes" arg)',
    '        detections = DetectionResult(',
    '            bboxes=[(20.0, 20.0, 40.0, 40.0)],',
    '            landmarks=[],',
    '            confidences=[1.0],',
    '        )',
    '        # process_frame(frame, frame_index, timestamp, state)',
    '        frame = np.zeros((64, 64, 3), dtype=np.uint8)',
    '        result = pipeline.process_frame(frame, 0, 0.0, None)',
    '',
    '        assert result.track_state == TrackState.CANDIDATE',
    '        assert result.is_redacted is False',
    '        # Output frame exists with correct shape',
    '        assert isinstance(result.result_frame, np.ndarray)',
    '',
    "# ======= Test 4: Gallery match -> CONFIRMED ======= #",
    'class TestGalleryMatchConfirmsRedaction:',
    '    def test_gallery_match_transitions_to_confirmed(self) -> None:',
    '        """Explicit gallery match (NOT detector confidence) triggers CONFIRMED."""',
    '        cfg = Config(effect_mode="mosaic")',
    '        pipeline = RedactionPipeline(cfg, detector=None)',
    '',
    '        # Set up gallery with one known profile embedding',
    '        gallery_db = {"subject1": [0.1] * 512}',
    '        matcher = GalleryMatcher(gallery_db=gallery_db)',
    '        pipeline._gallery = matcher',
    "",
    "        # Detect face first (goes UNSEEN -> CANDIDATE)",
    '        detections = DetectionResult(',
    '            bboxes=[(20.0, 20.0, 40.0, 40.0)],',
    '            landmarks=[],',
    '            confidences=[1.0],',
    '        )',
    '',
    '        # Advance recheck_interval_frames so gallery is queried (default=30)',
    '        frame = np.zeros((64, 64, 3), dtype=np.uint8)',
    "        for i in range(30):",
    '            pipeline.process_frame(frame.copy(), i, float(i), None)',
'',
    '        # After recheck_interval_frames the gallery match is evaluated.',
    '        assert pipeline.current_track_state == TrackState.CONFIRMED',
    '        assert pipeline._confirmed_profile_id == "subject1"',
    '',
    "# ======= Test 5: Transition UNSEEN -> CANDIDATE -> CONFIRMED ======= #",
    'class TestTransitionStates:',
    '    def test_unseen_becomes_candidate_on_detection(self) -> None:',
    '        """First detection transitions UNSEEN -> CANDIDATE."""',
    '        cfg = Config(effect_mode="mosaic")',
    '        pipeline = RedactionPipeline(cfg, detector=None)',
    '        assert pipeline.current_track_state == TrackState.UNSEEN',
    '',
    '        detections = DetectionResult(',
    '            bboxes=[(20.0, 20.0, 40.0, 40.0)],',
    '            landmarks=[],',
    '            confidences=[1.0],',
    '        )',
    '        frame = np.zeros((64, 64, 3), dtype=np.uint8)',
    '        result = pipeline.process_frame(frame.copy(), 0, 0.0, None)',
    '        assert result.track_state == TrackState.CANDIDATE',
    '',
    '    def test_candidate_no_detection_stays_goes_lost(self) -> None:',
    '        """When tracked face disappears briefly from CANDIDATE, goes LOST."""',
    '        cfg = Config(effect_mode="mosmic")',
    "        pipeline = RedactionPipeline(cfg, detector=None)",
    "        # First set it to CANDIDATE with a detection",
    '        detections = DetectionResult(',
    '            bboxes=[(20.0, 20.0, 40.0, 40.0)],',
    '            landmarks=[],',
    '            confidences=[1.0],',
    '        )',
    "        frame = np.zeros((64, 64, 3), dtype=np.uint8)",
    '        pipeline.process_frame(frame.copy(), 0, 0.0, None)',
    "",
    "        # Now no detection (empty bboxes) -- goes LOST",
    '        empty = DetectionResult(bboxes=[], landmarks=[], confidences=[])',
    '',
    '# ======= Test 6: StickerEffect loads valid PNG bytes ======= #',
    'class TestStickerInitWithBytes:',
    '    def test_sticker_accepts_raw_png_bytes(self) -> None:',
    '        """StickerEffect.__init__() accepts raw PNG bytes only; no mode string."""',
    '        img = Image.new("RGBA", (1, 1), (255, 255, 255, 255))',
    '        buf = BytesIO()',
    '        img.save(buf, format="PNG")',
    '        png_bytes = buf.getvalue()',
    '        effect = StickerEffect(png_bytes)',
    "        assert effect._sticker is not None",
    '',
    "# ======= Test 7: MatchDecision fields ======= #",
    'class TestDataClasses:',
    '    def test_match_decision_fields(self) -> None:',
    '        """MatchDecision fields are: is_target, confidence, reason_code, profile_id."""',
    '        m = MatchDecision(',
    '            is_target=True,',
    '            confidence=0.98,',
    '            reason_code="gallery_match",',
    '            profile_id="subject1",',
    '        )',
    '        assert m.is_target is True',
    '        assert m.confidence == pytest.approx(0.98)',
    '        assert m.profile_id == "subject1"',
    '',
    '    def test_embedding_result_fields(self) -> None:',
    '        """EmbeddingResult: vectors (list[np.ndarray]), model_revision (str)."""',
    '        vec = np.array([0.1] * 512, dtype=np.float32)',
    '        er = EmbeddingResult(vectors=[vec], model_revision="v1")',
    '        assert len(er.vectors) == 1',
    '        assert er.model_revision == "v1"',
    '',
    "class TestProcessResult:",
    '    def test_process_result_fields(self) -> None:',
    "        """ProcessResult has: result_frame, is_redacted, track_state, review_required."""",
    '        pr = ProcessResult(',
    '            result_frame=np.zeros((32, 32, 3), dtype=np.uint8),',
    '            is_redacted=True,',
    '            track_state=TrackState.CONFIRMED,',
    '',
    "# ======= Test 8: DetectionResult construction ======= #",
    'class TestDetectionResult:',
    '    def test_detection_result_bboxes(self) -> None:',
    '        """DetectionResult.bboxes must be set correctly at init."""',
    '        dr = DetectionResult(',
    '            bboxes=[(1.0, 2.0, 3.0, 4.0)],',
    '            landmarks=[np.zeros((5, 2), dtype=np.float32)],',
    '            confidences=[0.5],',
    '        )',
    '        assert dr.bboxes[0][0] == 1.0',
    '        assert dr.confidences[0] == pytest.approx(0.5)',
    "",
    "# ======= Test 9: face box type (from domain.types) ======= #",
    'class TestFaceBox:',
    '    def test_face_box_creation(self) -> None:',
    "        """face_box constructor accepts four numeric arguments."""",
    '        fb = FaceBox(x1=10, y1=10, x2=50, y2=50)',
    '        assert fb.x1 == 10',
    '        assert fb.x2 == 50',
    '',
    "# ======= Test 10: pipeline.state transitions when no faces ======= #",
    "class TestNoFaceDetection:",
    '    def test_unseen_no_detections_stays_unseen(self) -> None:',
    '        """With no detections and initial UNSEEN state, track remains UNSEEN."""',
    '        cfg = Config(effect_mode="mosaic")',
    '        pipeline = RedactionPipeline(cfg)',
    '',
    '        empty = DetectionResult(bboxes=[], landmarks=[], confidences=[])',
    '',
    "# ======= Test 11: process returns unmodified frame when not redacted ======= #",
    "class TestProcessNotRedacted:",
    '    def test_unredacted_frame_is_copy(self) -> None:',
    '        """When no identity confirmed, result_frame should be a copy of input."""',
    '        cfg = Config(effect_mode="mosaic")',
    '        pipeline = RedactionPipeline(cfg)',
    '',
]

# Verify imports before writing
import importlib.util

def _resolve(p):
    s = p.resolve()
    if str(SRC) not in str(s):
        raise SystemExit(f"Path leak: {s}")
    return s

spec_pipeline = importlib.util.spec_from_file_location("pipeline", _resolve(BASE / "src" / "consented_face_redactor" / "pipeline.py"))
mod_pipeline = importlib.util.module_from_spec(spec_pipeline)
try:
    spec_gallery = importlib.util.spec_from_file_location("gallery_matcher", _resolve(BASE / "src" / "consented_face_redactor" / "gallery_matcher.py"))
    __import__('sys').path.insert(0, str(SRC))
    mod_config_spec = _resolve(BASE / "src" / "__init__.py")
    
except (FileNotFoundError, PermissionError) as exc:
    print(f"Import check skipped: {exc}")

# Write output file
content = "\n".join(LINES) + "\n"
OUT.write_text(content, encoding="utf-8")
print(f"WROTE {len(content)} bytes -> {OUT.relative_to(BASE)}")
",